<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410075049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE foyer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, foyer_nom VARCHAR(100) NOT NULL, foyer_nombre_pers INT NOT NULL, foyer_date_creation DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE liste_course (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, liste_libelle VARCHAR(100) NOT NULL, liste_date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, liste_statut VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recette_libelle VARCHAR(150) NOT NULL, recette_description TEXT DEFAULT NULL, recette_difficulte VARCHAR(20) NOT NULL, recette_portion INT NOT NULL, recette_temps_prepa SMALLINT NOT NULL, recette_temps_cuisson SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE regime (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, regime_libelle VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_regime (user_id INT NOT NULL, regime_id INT NOT NULL, PRIMARY KEY (user_id, regime_id))');
        $this->addSql('CREATE INDEX IDX_CFD45141A76ED395 ON user_regime (user_id)');
        $this->addSql('CREATE INDEX IDX_CFD4514135E7D534 ON user_regime (regime_id)');
        $this->addSql('ALTER TABLE user_regime ADD CONSTRAINT FK_CFD45141A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_regime ADD CONSTRAINT FK_CFD4514135E7D534 FOREIGN KEY (regime_id) REFERENCES regime (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_regime DROP CONSTRAINT FK_CFD45141A76ED395');
        $this->addSql('ALTER TABLE user_regime DROP CONSTRAINT FK_CFD4514135E7D534');
        $this->addSql('DROP TABLE foyer');
        $this->addSql('DROP TABLE liste_course');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE regime');
        $this->addSql('DROP TABLE user_regime');
    }
}
