<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410083450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE recipe');
        $this->addSql('ALTER TABLE recette ADD recette_libelle VARCHAR(150) NOT NULL');
        $this->addSql('ALTER TABLE recette ADD recette_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE recette ADD recette_difficulte VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE recette ADD recette_portion INT NOT NULL');
        $this->addSql('ALTER TABLE recette ADD recette_temps_prepa SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE recette ADD recette_temps_cuisson SMALLINT NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recette_libelle VARCHAR(150) NOT NULL, recette_description TEXT DEFAULT NULL, recette_difficulte VARCHAR(20) NOT NULL, recette_portion INT NOT NULL, recette_temps_prepa SMALLINT NOT NULL, recette_temps_cuisson SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE recette DROP recette_libelle');
        $this->addSql('ALTER TABLE recette DROP recette_description');
        $this->addSql('ALTER TABLE recette DROP recette_difficulte');
        $this->addSql('ALTER TABLE recette DROP recette_portion');
        $this->addSql('ALTER TABLE recette DROP recette_temps_prepa');
        $this->addSql('ALTER TABLE recette DROP recette_temps_cuisson');
    }
}
