<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260601201951 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commentaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_visible BOOLEAN NOT NULL, user_id INT NOT NULL, recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F068BCA76ED395 ON commentaire (user_id)');
        $this->addSql('CREATE INDEX IDX_67F068BC89312FE9 ON commentaire (recette_id)');
        $this->addSql('CREATE TABLE note_recette (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valeur INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C81DA70AA76ED395 ON note_recette (user_id)');
        $this->addSql('CREATE INDEX IDX_C81DA70A89312FE9 ON note_recette (recette_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C81DA70AA76ED39589312FE9 ON note_recette (user_id, recette_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC89312FE9 FOREIGN KEY (recette_id) REFERENCES recette (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note_recette ADD CONSTRAINT FK_C81DA70AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note_recette ADD CONSTRAINT FK_C81DA70A89312FE9 FOREIGN KEY (recette_id) REFERENCES recette (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BCA76ED395');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC89312FE9');
        $this->addSql('ALTER TABLE note_recette DROP CONSTRAINT FK_C81DA70AA76ED395');
        $this->addSql('ALTER TABLE note_recette DROP CONSTRAINT FK_C81DA70A89312FE9');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE note_recette');
    }
}
