<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410080450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, categorie_libelle VARCHAR(80) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingredient_libelle VARCHAR(100) NOT NULL, ingredient_type VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE ingredient');
    }
}
