<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429163926 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE liste (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCF22AF4A76ED395 ON liste (user_id)');
        $this->addSql('CREATE TABLE liste_recette (liste_id INT NOT NULL, recette_id INT NOT NULL, PRIMARY KEY (liste_id, recette_id))');
        $this->addSql('CREATE INDEX IDX_F881FBC1E85441D8 ON liste_recette (liste_id)');
        $this->addSql('CREATE INDEX IDX_F881FBC189312FE9 ON liste_recette (recette_id)');
        $this->addSql('ALTER TABLE liste ADD CONSTRAINT FK_FCF22AF4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liste_recette ADD CONSTRAINT FK_F881FBC1E85441D8 FOREIGN KEY (liste_id) REFERENCES liste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE liste_recette ADD CONSTRAINT FK_F881FBC189312FE9 FOREIGN KEY (recette_id) REFERENCES recette (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE liste DROP CONSTRAINT FK_FCF22AF4A76ED395');
        $this->addSql('ALTER TABLE liste_recette DROP CONSTRAINT FK_F881FBC1E85441D8');
        $this->addSql('ALTER TABLE liste_recette DROP CONSTRAINT FK_F881FBC189312FE9');
        $this->addSql('DROP TABLE liste');
        $this->addSql('DROP TABLE liste_recette');
    }
}
