<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410073952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE foyer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, foyer_nom VARCHAR(100) NOT NULL, foyer_nombre_pers INT NOT NULL, foyer_date_creation DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recette_libelle VARCHAR(150) NOT NULL, recette_description TEXT DEFAULT NULL, recette_difficulte VARCHAR(20) NOT NULL, recette_portion INT NOT NULL, recette_temps_prepa SMALLINT NOT NULL, recette_temps_cuisson SMALLINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE regime (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, regime_libelle VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE foyer');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE regime');
    }
}
