<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412201354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE favori (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, favori_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, favori_user_id INT NOT NULL, favori_recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF85A2CCCAE277B2 ON favori (favori_user_id)');
        $this->addSql('CREATE INDEX IDX_EF85A2CC9A56C907 ON favori (favori_recette_id)');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CCCAE277B2 FOREIGN KEY (favori_user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CC9A56C907 FOREIGN KEY (favori_recette_id) REFERENCES recette (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE favori DROP CONSTRAINT FK_EF85A2CCCAE277B2');
        $this->addSql('ALTER TABLE favori DROP CONSTRAINT FK_EF85A2CC9A56C907');
        $this->addSql('DROP TABLE favori');
    }
}
