<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410083147 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contenir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenir_quantite INT NOT NULL, liste_course_id INT DEFAULT NULL, ingredient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3C914DFD4680FCB ON contenir (liste_course_id)');
        $this->addSql('CREATE INDEX IDX_3C914DFD933FE08C ON contenir (ingredient_id)');
        $this->addSql('CREATE TABLE etape (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, etape_numero INT NOT NULL, etape_libelle VARCHAR(150) NOT NULL, etape_description TEXT NOT NULL, etape_duree SMALLINT DEFAULT NULL, recette_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_285F75DD89312FE9 ON etape (recette_id)');
        $this->addSql('CREATE TABLE like_recette (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, like_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, like_user_id INT NOT NULL, like_recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A3629B3F4E399B6 ON like_recette (like_user_id)');
        $this->addSql('CREATE INDEX IDX_1A3629B32AA58F11 ON like_recette (like_recette_id)');
        $this->addSql('CREATE TABLE recette (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE repas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, repas_date DATE NOT NULL, repas_type VARCHAR(20) NOT NULL, foyer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A8D351B32B919A58 ON repas (foyer_id)');
        $this->addSql('CREATE TABLE stocker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stocker_quantite_dispo NUMERIC(10, 2) NOT NULL, foyer_id INT DEFAULT NULL, ingredient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AD495D2B919A58 ON stocker (foyer_id)');
        $this->addSql('CREATE INDEX IDX_AD495D933FE08C ON stocker (ingredient_id)');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFD4680FCB FOREIGN KEY (liste_course_id) REFERENCES liste_course (id)');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFD933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)');
        $this->addSql('ALTER TABLE etape ADD CONSTRAINT FK_285F75DD89312FE9 FOREIGN KEY (recette_id) REFERENCES recette (id)');
        $this->addSql('ALTER TABLE like_recette ADD CONSTRAINT FK_1A3629B3F4E399B6 FOREIGN KEY (like_user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE like_recette ADD CONSTRAINT FK_1A3629B32AA58F11 FOREIGN KEY (like_recette_id) REFERENCES recette (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE repas ADD CONSTRAINT FK_A8D351B32B919A58 FOREIGN KEY (foyer_id) REFERENCES foyer (id)');
        $this->addSql('ALTER TABLE stocker ADD CONSTRAINT FK_AD495D2B919A58 FOREIGN KEY (foyer_id) REFERENCES foyer (id)');
        $this->addSql('ALTER TABLE stocker ADD CONSTRAINT FK_AD495D933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFD4680FCB');
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFD933FE08C');
        $this->addSql('ALTER TABLE etape DROP CONSTRAINT FK_285F75DD89312FE9');
        $this->addSql('ALTER TABLE like_recette DROP CONSTRAINT FK_1A3629B3F4E399B6');
        $this->addSql('ALTER TABLE like_recette DROP CONSTRAINT FK_1A3629B32AA58F11');
        $this->addSql('ALTER TABLE repas DROP CONSTRAINT FK_A8D351B32B919A58');
        $this->addSql('ALTER TABLE stocker DROP CONSTRAINT FK_AD495D2B919A58');
        $this->addSql('ALTER TABLE stocker DROP CONSTRAINT FK_AD495D933FE08C');
        $this->addSql('DROP TABLE contenir');
        $this->addSql('DROP TABLE etape');
        $this->addSql('DROP TABLE like_recette');
        $this->addSql('DROP TABLE recette');
        $this->addSql('DROP TABLE repas');
        $this->addSql('DROP TABLE stocker');
    }
}
