<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414110130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE planning (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, planning_jour VARCHAR(10) NOT NULL, planning_moment VARCHAR(20) NOT NULL, user_id INT DEFAULT NULL, planning_recette_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D499BFF6A76ED395 ON planning (user_id)');
        $this->addSql('CREATE INDEX IDX_D499BFF610902E89 ON planning (planning_recette_id)');
        $this->addSql('ALTER TABLE planning ADD CONSTRAINT FK_D499BFF6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planning ADD CONSTRAINT FK_D499BFF610902E89 FOREIGN KEY (planning_recette_id) REFERENCES recette (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE planning DROP CONSTRAINT FK_D499BFF6A76ED395');
        $this->addSql('ALTER TABLE planning DROP CONSTRAINT FK_D499BFF610902E89');
        $this->addSql('DROP TABLE planning');
    }
}
